### PR TITLE
Starting Chapter3

### PR DESCRIPTION
**Pull request by edrubin**
I moved the Google doc outline of chapter 3 into Rmd on Github.

### CODE REVIEW

**Comment by danhammer** [comment]
Great! We won't merge into `master` until there is a working draft.

**Comment by SigmaMonstR** [comment]
Nice! working on the DIY and will work my way up from the bottom

**Comment by edrubin** [comment]
Just pushed some more updates to ch3 (finished data types and started on the object classes).

**Review by SigmaMonstR — COMMENTED** [review]
Looks good to me

**Pull request merged**
